import type {
  Agent,
  AIProvider,
  Capability,
  Integration,
  Model,
  Tool,
  Workflow,
} from "./types";

export const PROVIDERS: AIProvider[] = [
  {
    id: "sovi.router",
    name: "Sovi Router",
    kind: "internal",
    status: "available",
    description: "Default orchestration. Sovi decides model, agent, and tools.",
  },
  {
    id: "xai.grok",
    name: "xAI",
    kind: "cloud",
    status: "available",
    description: "Grok family via the Sovi gateway.",
    models: ["grok-4.5"],
  },
  {
    id: "local.llama",
    name: "Local models",
    kind: "local",
    status: "degraded",
    description: "On-device / LAN models. Mocked until the integrator maps them.",
  },
];

export const MODELS: Model[] = [
  {
    id: "grok-4.5",
    name: "Grok 4.5",
    providerId: "xai.grok",
    modality: ["text", "image", "code"],
    streaming: true,
    status: "available",
  },
  {
    id: "sovi.auto",
    name: "Sovi decides",
    providerId: "sovi.router",
    modality: ["text", "image", "audio", "video", "code"],
    streaming: true,
    status: "available",
  },
  {
    id: "local.fast",
    name: "Local fast",
    providerId: "local.llama",
    modality: ["text"],
    streaming: true,
    status: "degraded",
  },
];

type CapInput = Omit<Capability, "enabled" | "available" | "status" | "health"> &
  Partial<Pick<Capability, "enabled" | "available" | "status" | "health">>;

function cap(partial: CapInput): Capability {
  return {
    enabled: true,
    available: true,
    status: "available",
    health: "healthy",
    ...partial,
  };
}

export const CAPABILITIES: Capability[] = [
  cap({
    id: "chat.reasoning",
    name: "Conversation",
    description: "General reasoning, writing, and Q&A through Sovi.",
    category: "chat",
    type: "native.chat",
    streaming: true,
    voice: true,
    files: true,
    provider: "sovi.router",
    model: "sovi.auto",
    supportedInputs: ["text", "image", "file", "audio"],
    supportedOutputs: ["text", "markdown", "artifact"],
    ui: { icon: "MessageSquare", renderer: "native", nav: true, order: 0 },
  }),
  cap({
    id: "voice.mode",
    name: "Voice mode",
    description: "Hands-free listening and spoken replies.",
    category: "speech",
    type: "native.voice",
    voice: true,
    streaming: true,
    ui: { icon: "AudioLines", renderer: "native", nav: false, accent: "voice" },
  }),
  cap({
    id: "speech.tts",
    name: "Speech generation",
    description: "Turn text into spoken audio.",
    category: "speech",
    type: "media.tts",
    ui: { icon: "Volume2", renderer: "enhanced" },
    inputSchema: {
      type: "object",
      required: ["text"],
      properties: {
        text: { type: "string", title: "Text" },
        voice: { type: "string", title: "Voice", enum: ["eve", "default"] },
      },
    },
  }),
  cap({
    id: "speech.stt",
    name: "Speech recognition",
    description: "Transcribe microphone input into text.",
    category: "stt",
    type: "media.stt",
    ui: { icon: "Mic", renderer: "enhanced" },
  }),
  cap({
    id: "research.web",
    name: "Research",
    description: "Investigate a question with sources and a structured answer.",
    category: "research",
    type: "enhanced.research",
    streaming: true,
    ui: { icon: "Telescope", renderer: "enhanced", nav: false, accent: "research" },
    inputSchema: {
      type: "object",
      required: ["query"],
      properties: {
        query: { type: "string", title: "Research question" },
        depth: { type: "string", enum: ["quick", "standard", "deep"], default: "standard" },
      },
    },
  }),
  cap({
    id: "web.intelligence",
    name: "Web intelligence",
    description: "Browse and extract from the public web.",
    category: "web",
    type: "tool.web",
    ui: { icon: "Globe", renderer: "generic" },
  }),
  cap({
    id: "coding.workspace",
    name: "Coding workspace",
    description: "Design, write, and iterate on software with artifacts.",
    category: "coding",
    type: "native.coding",
    streaming: true,
    files: true,
    ui: { icon: "Code2", renderer: "native", accent: "code" },
  }),
  cap({
    id: "software.build",
    name: "Software development",
    description: "Multi-file application scaffolding and iteration.",
    category: "software",
    type: "enhanced.software",
    ui: { icon: "AppWindow", renderer: "enhanced" },
  }),
  cap({
    id: "media.image.generate",
    name: "Image generation",
    description: "Create images from a description.",
    category: "image",
    type: "native.image",
    media: true,
    ui: { icon: "Image", renderer: "native", accent: "create", nav: false },
    inputSchema: {
      type: "object",
      required: ["prompt"],
      properties: {
        prompt: { type: "string", title: "Prompt" },
        aspect: { type: "string", enum: ["1:1", "16:9", "9:16", "4:3"], default: "1:1" },
      },
    },
  }),
  cap({
    id: "media.image.edit",
    name: "Image editing",
    description: "Edit an existing image with natural language.",
    category: "image-edit",
    type: "native.image-edit",
    media: true,
    files: true,
    ui: { icon: "Pencil", renderer: "native", accent: "create" },
    inputSchema: {
      type: "object",
      required: ["prompt", "image"],
      properties: {
        prompt: { type: "string", title: "Edit instructions" },
        image: { type: "string", title: "Image", format: "uri" },
      },
    },
  }),
  cap({
    id: "media.video.generate",
    name: "Video generation",
    description: "Generate short video clips from a prompt.",
    category: "video",
    type: "enhanced.video",
    media: true,
    ui: { icon: "Film", renderer: "enhanced", accent: "create" },
    inputSchema: {
      type: "object",
      required: ["prompt"],
      properties: {
        prompt: { type: "string", title: "Prompt" },
        duration: { type: "string", enum: ["6", "10"], default: "6" },
      },
    },
  }),
  cap({
    id: "media.audio.generate",
    name: "Audio generation",
    description: "Generate music, ambience, or voice beds.",
    category: "audio",
    type: "enhanced.audio",
    media: true,
    ui: { icon: "Music", renderer: "enhanced" },
    inputSchema: {
      type: "object",
      required: ["prompt"],
      properties: { prompt: { type: "string", title: "Prompt" } },
    },
  }),
  cap({
    id: "files.documents",
    name: "Documents",
    description: "Read, summarize, and transform files and documents.",
    category: "documents",
    type: "enhanced.files",
    files: true,
    ui: { icon: "FileText", renderer: "enhanced" },
  }),
  cap({
    id: "files.library",
    name: "Files",
    description: "Workspace file library attached to conversations and projects.",
    category: "files",
    type: "enhanced.files",
    files: true,
    ui: { icon: "Folder", renderer: "enhanced", nav: false },
  }),
  cap({
    id: "agents.orchestrator",
    name: "Agent orchestrator",
    description: "Plan and run multi-step agents on the user's behalf.",
    category: "agents",
    type: "native.agents",
    ui: { icon: "Bot", renderer: "native", nav: true, order: 20 },
  }),
  cap({
    id: "agents.research",
    name: "Research agent",
    description: "Autonomous literature and landscape research.",
    category: "agents",
    type: "enhanced.agent",
    ui: { icon: "Radar", renderer: "enhanced" },
  }),
  cap({
    id: "agents.coding",
    name: "Coding agent",
    description: "Delegated implementation, tests, and iteration.",
    category: "agents",
    type: "enhanced.agent",
    ui: { icon: "Terminal", renderer: "enhanced" },
  }),
  cap({
    id: "workflows.runner",
    name: "Workflows",
    description: "Run saved multi-step workflows.",
    category: "workflows",
    type: "enhanced.workflow",
    ui: { icon: "Workflow", renderer: "enhanced", nav: true, order: 30 },
  }),
  cap({
    id: "automations.engine",
    name: "Automations",
    description: "Scheduled and event-driven automations.",
    category: "automations",
    type: "enhanced.automation",
    ui: { icon: "Zap", renderer: "enhanced" },
  }),
  cap({
    id: "memory.longterm",
    name: "Memory",
    description: "Hooks into Sovi's existing memory — this UI does not own it.",
    category: "memory",
    type: "enhanced.memory",
    ui: { icon: "Brain", renderer: "enhanced", nav: true, order: 40 },
  }),
  cap({
    id: "knowledge.retrieval",
    name: "Knowledge retrieval",
    description: "Retrieve project and personal knowledge into context.",
    category: "knowledge",
    type: "enhanced.knowledge",
    ui: { icon: "Library", renderer: "enhanced" },
  }),
  cap({
    id: "apis.gateway",
    name: "External APIs",
    description: "Call registered HTTP APIs through Sovi.",
    category: "apis",
    type: "generic.api",
    ui: { icon: "Plug", renderer: "generic" },
    inputSchema: {
      type: "object",
      required: ["action"],
      properties: {
        action: { type: "string", title: "Action" },
        payload: { type: "string", title: "JSON payload" },
      },
    },
  }),
  cap({
    id: "mcp.tools",
    name: "MCP tools",
    description: "Model Context Protocol style tools and services.",
    category: "mcp",
    type: "generic.mcp",
    ui: { icon: "Blocks", renderer: "generic" },
  }),
  cap({
    id: "computer.browser",
    name: "Computer / browser use",
    description: "Operate a browser or computer on the user's behalf.",
    category: "computer-use",
    type: "enhanced.computer",
    enabled: true,
    available: false,
    status: "unavailable",
    health: "down",
    ui: { icon: "Monitor", renderer: "enhanced", nav: false },
  }),
  cap({
    id: "business.ops",
    name: "Business systems",
    description: "Personal business operations surface.",
    category: "business",
    type: "generic.business",
    status: "degraded",
    health: "degraded",
    ui: { icon: "Briefcase", renderer: "generic" },
    inputSchema: {
      type: "object",
      required: ["task"],
      properties: { task: { type: "string", title: "Task" } },
    },
  }),
  cap({
    id: "personal.life",
    name: "Personal life systems",
    description: "Calendar, notes, and life-ops hooks.",
    category: "personal",
    type: "generic.personal",
    ui: { icon: "Heart", renderer: "generic" },
    inputSchema: {
      type: "object",
      required: ["note"],
      properties: { note: { type: "string", title: "Note" } },
    },
  }),
  cap({
    id: "simulation.generic",
    name: "Simulation",
    description: "Run a simulation from a schema. Generic renderer example.",
    category: "simulation",
    type: "generic.simulation",
    ui: { icon: "Orbit", renderer: "generic" },
    inputSchema: {
      type: "object",
      required: ["scenario"],
      properties: {
        scenario: { type: "string", title: "Scenario" },
        steps: { type: "number", title: "Steps", default: 12, minimum: 1, maximum: 100 },
      },
    },
    outputSchema: {
      type: "object",
      properties: {
        summary: { type: "string" },
        series: { type: "string" },
      },
    },
  }),
  cap({
    id: "physical.cad",
    name: "Bits to atoms",
    description: "CAD, fabrication, and physical-world capabilities.",
    category: "physical",
    type: "generic.physical",
    enabled: true,
    available: false,
    status: "unavailable",
    health: "unknown",
    ui: { icon: "Box", renderer: "generic", accent: "physical", nav: false },
  }),
];

export const AGENTS: Agent[] = [
  {
    id: "agent.research",
    name: "Landscape",
    description: "Maps prior art, competitors, and open questions.",
    status: "available",
    tools: ["tool.web.search", "tool.memory.search"],
    model: "sovi.auto",
  },
  {
    id: "agent.builder",
    name: "Builder",
    description: "Turns requirements into prototypes and tests.",
    status: "available",
    tools: ["tool.files.write", "tool.terminal"],
    model: "grok-4.5",
  },
  {
    id: "agent.ops",
    name: "Ops",
    description: "Watches jobs, retries, and health.",
    status: "available",
    tools: ["tool.system.status"],
  },
  {
    id: "agent.physical",
    name: "Fabricator",
    description: "Would drive CAD and BOM workflows when available.",
    status: "unavailable",
  },
];

export const TOOLS: Tool[] = [
  {
    id: "tool.web.search",
    name: "Web search",
    description: "Search the public web.",
    status: "available",
    mcp: false,
  },
  {
    id: "tool.web.read",
    name: "Read page",
    description: "Extract a URL into context.",
    status: "available",
  },
  {
    id: "tool.memory.search",
    name: "Memory search",
    description: "Query Sovi memory. Does not replace the backend store.",
    status: "available",
  },
  {
    id: "tool.files.write",
    name: "Write file",
    description: "Create or update a workspace file.",
    status: "available",
  },
  {
    id: "tool.terminal",
    name: "Terminal",
    description: "Run a sandboxed command.",
    status: "degraded",
  },
  {
    id: "tool.system.status",
    name: "System status",
    description: "Read service health.",
    status: "available",
  },
  {
    id: "mcp.example.notes",
    name: "Notes MCP",
    description: "Example MCP-style tool, schema-driven.",
    status: "available",
    mcp: true,
    inputSchema: {
      type: "object",
      required: ["query"],
      properties: { query: { type: "string", title: "Query" } },
    },
  },
];

export const WORKFLOWS: Workflow[] = [
  {
    id: "wf.research-to-prototype",
    name: "Research → prototype",
    description: "Investigate an idea, then scaffold a prototype if it is buildable.",
    status: "available",
    steps: [
      { id: "s1", name: "Research landscape", capabilityId: "research.web" },
      { id: "s2", name: "Decide feasibility", capabilityId: "chat.reasoning" },
      { id: "s3", name: "Build prototype", capabilityId: "coding.workspace" },
    ],
  },
  {
    id: "wf.weekly-review",
    name: "Weekly review",
    description: "Summarize memory, projects, and open tasks.",
    status: "available",
    steps: [
      { id: "s1", name: "Recall", capabilityId: "memory.longterm" },
      { id: "s2", name: "Summarize", capabilityId: "chat.reasoning" },
    ],
  },
];

export const INTEGRATIONS: Integration[] = [
  { id: "int.github", name: "GitHub", kind: "scm", status: "unavailable" },
  { id: "int.drive", name: "Files gateway", kind: "files", status: "available" },
];
