/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppArtifactsRouteImport } from './routes/_app/artifacts'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppCapabilitiesRouteImport } from './routes/_app/capabilities'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as DevDesignSystemRouteImport } from './routes/dev/design-system'
import { Route as AppCConversationIdRouteImport } from './routes/_app/c.$conversationId'
import { Route as AppCapabilitiesIndexRouteImport } from './routes/_app/capabilities.index'
import { Route as AppCapabilitiesCapabilityIdRouteImport } from './routes/_app/capabilities.$capabilityId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSoviChatRouteImport } from './routes/api/sovi/chat'
import { Route as ApiSoviImageRouteImport } from './routes/api/sovi/image'
import { Route as ApiSoviStatusRouteImport } from './routes/api/sovi/status'
import { Route as ApiSoviTtsRouteImport } from './routes/api/sovi/tts'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesRoute = AppCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppCapabilitiesIndexRoute = AppCapabilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCapabilitiesRoute,
} as any)
const AppCapabilitiesCapabilityIdRoute =
  AppCapabilitiesCapabilityIdRouteImport.update({
    id: '/$capabilityId',
    path: '/$capabilityId',
    getParentRoute: () => AppCapabilitiesRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoviChatRoute = ApiSoviChatRouteImport.update({
  id: '/api/sovi/chat',
  path: '/api/sovi/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoviImageRoute = ApiSoviImageRouteImport.update({
  id: '/api/sovi/image',
  path: '/api/sovi/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoviStatusRoute = ApiSoviStatusRouteImport.update({
  id: '/api/sovi/status',
  path: '/api/sovi/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoviTtsRoute = ApiSoviTtsRouteImport.update({
  id: '/api/sovi/tts',
  path: '/api/sovi/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AppAgentsRoute
  '/artifacts': typeof AppArtifactsRoute
  '/automations': typeof AppAutomationsRoute
  '/capabilities': typeof AppCapabilitiesRouteWithChildren
  '/media': typeof AppMediaRoute
  '/memory': typeof AppMemoryRoute
  '/projects': typeof AppProjectsRoute
  '/system': typeof AppSystemRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/capabilities/$capabilityId': typeof AppCapabilitiesCapabilityIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sovi/chat': typeof ApiSoviChatRoute
  '/api/sovi/image': typeof ApiSoviImageRoute
  '/api/sovi/status': typeof ApiSoviStatusRoute
  '/api/sovi/tts': typeof ApiSoviTtsRoute
  '/capabilities/': typeof AppCapabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agents': typeof AppAgentsRoute
  '/artifacts': typeof AppArtifactsRoute
  '/automations': typeof AppAutomationsRoute
  '/media': typeof AppMediaRoute
  '/memory': typeof AppMemoryRoute
  '/projects': typeof AppProjectsRoute
  '/system': typeof AppSystemRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/': typeof AppIndexRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/capabilities/$capabilityId': typeof AppCapabilitiesCapabilityIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sovi/chat': typeof ApiSoviChatRoute
  '/api/sovi/image': typeof ApiSoviImageRoute
  '/api/sovi/status': typeof ApiSoviStatusRoute
  '/api/sovi/tts': typeof ApiSoviTtsRoute
  '/capabilities': typeof AppCapabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/artifacts': typeof AppArtifactsRoute
  '/_app/automations': typeof AppAutomationsRoute
  '/_app/capabilities': typeof AppCapabilitiesRouteWithChildren
  '/_app/media': typeof AppMediaRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/system': typeof AppSystemRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$conversationId': typeof AppCConversationIdRoute
  '/_app/capabilities/$capabilityId': typeof AppCapabilitiesCapabilityIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/sovi/chat': typeof ApiSoviChatRoute
  '/api/sovi/image': typeof ApiSoviImageRoute
  '/api/sovi/status': typeof ApiSoviStatusRoute
  '/api/sovi/tts': typeof ApiSoviTtsRoute
  '/_app/capabilities/': typeof AppCapabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/artifacts'
    | '/automations'
    | '/capabilities'
    | '/media'
    | '/memory'
    | '/projects'
    | '/system'
    | '/dev/design-system'
    | '/c/$conversationId'
    | '/capabilities/$capabilityId'
    | '/api/auth/$'
    | '/api/sovi/chat'
    | '/api/sovi/image'
    | '/api/sovi/status'
    | '/api/sovi/tts'
    | '/capabilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agents'
    | '/artifacts'
    | '/automations'
    | '/media'
    | '/memory'
    | '/projects'
    | '/system'
    | '/dev/design-system'
    | '/'
    | '/c/$conversationId'
    | '/capabilities/$capabilityId'
    | '/api/auth/$'
    | '/api/sovi/chat'
    | '/api/sovi/image'
    | '/api/sovi/status'
    | '/api/sovi/tts'
    | '/capabilities'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/agents'
    | '/_app/artifacts'
    | '/_app/automations'
    | '/_app/capabilities'
    | '/_app/media'
    | '/_app/memory'
    | '/_app/projects'
    | '/_app/system'
    | '/dev/design-system'
    | '/_app/'
    | '/_app/c/$conversationId'
    | '/_app/capabilities/$capabilityId'
    | '/api/auth/$'
    | '/api/sovi/chat'
    | '/api/sovi/image'
    | '/api/sovi/status'
    | '/api/sovi/tts'
    | '/_app/capabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSoviChatRoute: typeof ApiSoviChatRoute
  ApiSoviImageRoute: typeof ApiSoviImageRoute
  ApiSoviStatusRoute: typeof ApiSoviStatusRoute
  ApiSoviTtsRoute: typeof ApiSoviTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities': {
      id: '/_app/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof AppCapabilitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/c/$conversationId': {
      id: '/_app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capabilities/': {
      id: '/_app/capabilities/'
      path: '/'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof AppCapabilitiesIndexRouteImport
      parentRoute: typeof AppCapabilitiesRoute
    }
    '/_app/capabilities/$capabilityId': {
      id: '/_app/capabilities/$capabilityId'
      path: '/$capabilityId'
      fullPath: '/capabilities/$capabilityId'
      preLoaderRoute: typeof AppCapabilitiesCapabilityIdRouteImport
      parentRoute: typeof AppCapabilitiesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sovi/chat': {
      id: '/api/sovi/chat'
      path: '/api/sovi/chat'
      fullPath: '/api/sovi/chat'
      preLoaderRoute: typeof ApiSoviChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sovi/image': {
      id: '/api/sovi/image'
      path: '/api/sovi/image'
      fullPath: '/api/sovi/image'
      preLoaderRoute: typeof ApiSoviImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sovi/status': {
      id: '/api/sovi/status'
      path: '/api/sovi/status'
      fullPath: '/api/sovi/status'
      preLoaderRoute: typeof ApiSoviStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sovi/tts': {
      id: '/api/sovi/tts'
      path: '/api/sovi/tts'
      fullPath: '/api/sovi/tts'
      preLoaderRoute: typeof ApiSoviTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCapabilitiesRouteChildren {
  AppCapabilitiesCapabilityIdRoute: typeof AppCapabilitiesCapabilityIdRoute
  AppCapabilitiesIndexRoute: typeof AppCapabilitiesIndexRoute
}

const AppCapabilitiesRouteChildren: AppCapabilitiesRouteChildren = {
  AppCapabilitiesCapabilityIdRoute: AppCapabilitiesCapabilityIdRoute,
  AppCapabilitiesIndexRoute: AppCapabilitiesIndexRoute,
}

const AppCapabilitiesRouteWithChildren = AppCapabilitiesRoute._addFileChildren(
  AppCapabilitiesRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppCapabilitiesRoute: typeof AppCapabilitiesRouteWithChildren
  AppMediaRoute: typeof AppMediaRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppArtifactsRoute: AppArtifactsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppCapabilitiesRoute: AppCapabilitiesRouteWithChildren,
  AppMediaRoute: AppMediaRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSystemRoute: AppSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  DevDesignSystemRoute: DevDesignSystemRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSoviChatRoute: ApiSoviChatRoute,
  ApiSoviImageRoute: ApiSoviImageRoute,
  ApiSoviStatusRoute: ApiSoviStatusRoute,
  ApiSoviTtsRoute: ApiSoviTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
